encoding: utf-8
name: Karthik Gopinath
url: http://karthikgopinath.com
author:
  name: Karthik Gopinath
  email: karthik.g.haritz@gmail.com
description: Postdoctoral Research Fellow at MGH & Harvard Medical School. Advancing AI and computational biophysics to unravel molecular interactions.
permalink: /posts/:title/
include: ['_pages']
